
// Jamal Moubarak
// Project 4
// VFW 1303

var json = {
	"client1": {
		"id": ["Client ID:", "12345678"],
		"group": ["Install:", "POS"],
		"compname": ["Company Name:", "Eskatech"],
		"contname": ["Contact Name:", "Jamal Moubarak"],
		"contphone": ["Contact Phone #", "734-819-1211"],
		"contemail": ["Contact Email:", "jamal@eskatech.com"],
		"date": ["Install Date:", "2013-03-14"],
		"ipaddress": ["Ip Address:", "192.168.001.099"],
		"sysuser": ["System Username:", "admin"],
		"syspass": ["System Password:", "admin"],
		"installed": ["The client has these systems installed:", "POS"],
		"warranty": ["The client has this warranty:", "1 Year"],
		"quanity": ["Quanity:", "4"],
		"price": ["Price", "$4595.00"],
		"notes": ["Notes:", "We installed 4 POS systems at the front counter off of a network switch we installed"]			
	},
	"client2":{
		"id": ["Client ID:", "87654321"],
		"group": ["Install:", "Surveillance"],
		"compname": ["Company Name:", "Fairfield Inn"],
		"contname": ["Contact Name:", "John Smith"],
		"contphone": ["Contact Phone #", "555-555-2233"],
		"contemail": ["Contact Email:", "john@gmail.com"],
		"date": ["Install Date:", "2013-03-10"],
		"ipaddress": ["Ip Address:", "192.168.001.100"],
		"sysuser": ["System Username:", "john"],
		"syspass": ["System Password:", "123456"],
		"installed": ["The client has these systems installed:", "Surveillance"],
		"warranty": ["The client has this warranty:", "3 Year"],
		"quanity": ["Quanity:", "32"],
		"price": ["Price", "$7995.00"],
		"notes": ["Notes:", "We installed 8 cams 1st floor, 8 2nd floor, 8 3rd floor, 8 outside"]
	},
	"client3":{
		"id": ["Client ID:", "23456789"],
		"group": ["Install:", "Network"],
		"compname": ["Company Name:", "Del Taco"],
		"contname": ["Contact Name:", "Jane Smith"],
		"contphone": ["Contact Phone #", "555-555-1111"],
		"contemail": ["Contact Email:", "jane@gmail.com"],
		"date": ["Install Date:", "2012-02-30"],
		"ipaddress": ["Ip Address:", "192.168.001.99"],
		"sysuser": ["System Username:", "jane"],
		"syspass": ["System Password:", "deltaco"],
		"installed": ["The client has these systems installed:", "Network"],
		"warranty": ["The client has this warranty:", "3 Year"],
		"quanity": ["Quanity:", "16"],
		"price": ["Price", "$10995.00"],
		"notes": ["Notes:", "We installed 16 cams and a sonic firewall for free wi-fi"]
	},
	"client4":{
		"id": ["Client ID:", "98765432"],
		"group": ["Install:", "AudioVideo"],
		"compname": ["Company Name:", "Petes Garage"],
		"contname": ["Contact Name:", "Pete George"],
		"contphone": ["Contact Phone #", "555-555-2222"],
		"contemail": ["Contact Email:", "pete@gmail.com"],
		"date": ["Install Date:", "2013-01-24"],
		"ipaddress": ["Ip Address:", "192.168.000.99"],
		"sysuser": ["System Username:", "guest"],
		"syspass": ["System Password:", "123456"],
		"installed": ["The client has these systems installed:", "Audio / Video"],
		"warranty": ["The client has this warranty:", "90 Days"],
		"quanity": ["Quanity:", "4"],
		"price": ["Price", "$3995.00"],
		"notes": ["Notes:", "We installed 4 speakers in the customer area and install a password protected linksys router so they can give wifi to customers."]
	},
		"client5": {
		"id": ["Client ID:", "95022888"],
		"group": ["Install:", "POS"],
		"compname": ["Company Name:", "Jacksons Fencing"],
		"contname": ["Contact Name:", "James Jackson"],
		"contphone": ["Contact Phone #", "724-203-2300"],
		"contemail": ["Contact Email:", "james@jacksonsfencing.com"],
		"date": ["Install Date:", "2013-01-04"],
		"ipaddress": ["Ip Address:", "10.0.1.1"],
		"sysuser": ["System Username:", "admin"],
		"syspass": ["System Password:", "admin"],
		"installed": ["The client has these systems installed:", "POS"],
		"warranty": ["The client has this warranty:", "3 Year"],
		"quanity": ["Quanity:", "10"],
		"price": ["Price", "$14595.00"],
		"notes": ["Notes:", "This is a Test."]			
	},
	"client6":{
		"id": ["Client ID:", "98585054"],
		"group": ["Install:", "Surveillance"],
		"compname": ["Company Name:", "ParAid Medical"],
		"contname": ["Contact Name:", "Allan Marsh"],
		"contphone": ["Contact Phone #", "412-319-3900"],
		"contemail": ["Contact Email:", "allanmarsh@gmail.com"],
		"date": ["Install Date:", "2012-07-14"],
		"ipaddress": ["Ip Address:", "192.168.1.220"],
		"sysuser": ["System Username:", "Allan"],
		"syspass": ["System Password:", "123456"],
		"installed": ["The client has these systems installed:", "Surveillance"],
		"warranty": ["The client has this warranty:", "5 Year"],
		"quanity": ["Quanity:", "16"],
		"price": ["Price", "$3995.00"],
		"notes": ["Notes:", "This is another Test."]
	},
	"client7":{
		"id": ["Client ID:", "71434983"],
		"group": ["Install:", "Network"],
		"compname": ["Company Name:", "HAAS Automation"],
		"contname": ["Contact Name:", "Alex May"],
		"contphone": ["Contact Phone #", "724-218-2800"],
		"contemail": ["Contact Email:", "alexmay@gmail.com"],
		"date": ["Install Date:", "2012-02-21"],
		"ipaddress": ["Ip Address:", "192.168.2.1"],
		"sysuser": ["System Username:", "admin"],
		"syspass": ["System Password:", "password"],
		"installed": ["The client has these systems installed:", "Network"],
		"warranty": ["The client has this warranty:", "1 Year"],
		"quanity": ["Quanity:", "1"],
		"price": ["Price", "$995.00"],
		"notes": ["Notes:", "Alex is a great contact person to have."]
	},
	"client8":{
		"id": ["Client ID:", "76408706"],
		"group": ["Install:", "AudioVideo"],
		"compname": ["Company Name:", "Bassetts Foods"],
		"contname": ["Contact Name:", "Stephanie Hawkins"],
		"contphone": ["Contact Phone #", "412-317-3700"],
		"contemail": ["Contact Email:", "stephaniehawkins@bassetts.com"],
		"date": ["Install Date:", "2013-03-18"],
		"ipaddress": ["Ip Address:", "192.168.11.1"],
		"sysuser": ["System Username:", "Stephanie"],
		"syspass": ["System Password:", "admin"],
		"installed": ["The client has these systems installed:", "Audio / Video"],
		"warranty": ["The client has this warranty:", "90 Days"],
		"quanity": ["Quanity:", "2"],
		"price": ["Price", "$495.00"],
		"notes": ["Notes:", "We installed 2 speakers by the register."]
	},
		"client9": {
		"id": ["Client ID:", "56748923"],
		"group": ["Install:", "POS"],
		"compname": ["Company Name:", "Scrubs Pub"],
		"contname": ["Contact Name:", "Beth Walton"],
		"contphone": ["Contact Phone #", "412-517-5700"],
		"contemail": ["Contact Email:", "bwalton5700@yahoo.com.com"],
		"date": ["Install Date:", "2012-06-23"],
		"ipaddress": ["Ip Address:", "192.168.1.254"],
		"sysuser": ["System Username:", "admin"],
		"syspass": ["System Password:", "admin"],
		"installed": ["The client has these systems installed:", "POS"],
		"warranty": ["The client has this warranty:", "5 Year"],
		"quanity": ["Quanity:", "4"],
		"price": ["Price", "$12595.00"],
		"notes": ["Notes:", "The customer has an electrical issue which we let them know their warranty is void if it is not fixed."]			
	},
	"client10":{
		"id": ["Client ID:", "20628884"],
		"group": ["Install:", "Surveillance"],
		"compname": ["Company Name:", "Clazel Theatre"],
		"contname": ["Contact Name:", "Erica Hall"],
		"contphone": ["Contact Phone #", "412-318-3800"],
		"contemail": ["Contact Email:", "babyhallsmommie@gmail.com"],
		"date": ["Install Date:", "2012-02-28"],
		"ipaddress": ["Ip Address:", "10.0.0.138"],
		"sysuser": ["System Username:", "erica"],
		"syspass": ["System Password:", "666666"],
		"installed": ["The client has these systems installed:", "Surveillance"],
		"warranty": ["The client has this warranty:", "1 Year"],
		"quanity": ["Quanity:", "8"],
		"price": ["Price", "$2995.00"],
		"notes": ["Notes:", "We installed 8 cameras inside the theatre with the DVR in the office."]
	},
	"client11":{
		"id": ["Client ID:", "35133340"],
		"group": ["Install:", "Network"],
		"compname": ["Company Name:", "Wireless Boys"],
		"contname": ["Contact Name:", "Donald Chung"],
		"contphone": ["Contact Phone #", "412-208-2828"],
		"contemail": ["Contact Email:", "donaldchung@gmail.com"],
		"date": ["Install Date:", "2012-10-04"],
		"ipaddress": ["Ip Address:", "72.124.168.153"],
		"sysuser": ["System Username:", "donald"],
		"syspass": ["System Password:", "111111"],
		"installed": ["The client has these systems installed:", "Network"],
		"warranty": ["The client has this warranty:", "3 Year"],
		"quanity": ["Quanity:", "1"],
		"price": ["Price", "$1995.00"],
		"notes": ["Notes:", "We installed WiFi for the customers to use when in the store."]
	},
	"client12":{
		"id": ["Client ID:", "44637039"],
		"group": ["Install:", "AudioVideo"],
		"compname": ["Company Name:", "Ford Motor Company"],
		"contname": ["Contact Name:", "Paul Woods"],
		"contphone": ["Contact Phone #", "412-481-6022"],
		"contemail": ["Contact Email:", "paulwoods@gmail.com"],
		"date": ["Install Date:", "2011-08-08"],
		"ipaddress": ["Ip Address:", "192.168.1.1"],
		"sysuser": ["System Username:", "paul"],
		"syspass": ["System Password:", "woods"],
		"installed": ["The client has these systems installed:", "Audio / Video"],
		"warranty": ["The client has this warranty:", "3 Year"],
		"quanity": ["Quanity:", "16"],
		"price": ["Price", "$8995.00"],
		"notes": ["Notes:", "We installed 16 speakers in the employee break areas."]
	},
		"client13": {
		"id": ["Client ID:", "65748084"],
		"group": ["Install:", "POS"],
		"compname": ["Company Name:", "Liban Cafe"],
		"contname": ["Contact Name:", "Karen Puckett"],
		"contphone": ["Contact Phone #", "412-714-7400"],
		"contemail": ["Contact Email:", "karenpuckett@gmail.com"],
		"date": ["Install Date:", "2011-03-17"],
		"ipaddress": ["Ip Address:", "192.168.0.127"],
		"sysuser": ["System Username:", "admin"],
		"syspass": ["System Password:", "libancafe"],
		"installed": ["The client has these systems installed:", "POS"],
		"warranty": ["The client has this warranty:", "5 Year"],
		"quanity": ["Quanity:", "1"],
		"price": ["Price", "$4595.00"],
		"notes": ["Notes:", "We installed 1 POS system at the customer checkout area."]			
	},
	"client14":{
		"id": ["Client ID:", "74929233"],
		"group": ["Install:", "Surveillance"],
		"compname": ["Company Name:", "Kisses Showgirls"],
		"contname": ["Contact Name:", "Tim Watts"],
		"contphone": ["Contact Phone #", "412-749-4101"],
		"contemail": ["Contact Email:", "kisses419@gmail.com"],
		"date": ["Install Date:", "2012-04-20"],
		"ipaddress": ["Ip Address:", "192.168.0.1"],
		"sysuser": ["System Username:", "timwatts"],
		"syspass": ["System Password:", "password"],
		"installed": ["The client has these systems installed:", "Surveillance"],
		"warranty": ["The client has this warranty:", "3 Year"],
		"quanity": ["Quanity:", "25"],
		"price": ["Price", "$8995.00"],
		"notes": ["Notes:", "We installed 25 cameras on the 32 channel system.  We let the customer know they have room to add 7 more cameras."]
	},
	"client15":{
		"id": ["Client ID:", "24155242"],
		"group": ["Install:", "Network"],
		"compname": ["Company Name:", "Blue Agave"],
		"contname": ["Contact Name:", "Marion Moon"],
		"contphone": ["Contact Phone #", "724-206-2600"],
		"contemail": ["Contact Email:", "marionmoon@gmail.com"],
		"date": ["Install Date:", "2012-07-07"],
		"ipaddress": ["Ip Address:", "192.169.0.99"],
		"sysuser": ["System Username:", "marion"],
		"syspass": ["System Password:", "888888"],
		"installed": ["The client has these systems installed:", "Network"],
		"warranty": ["The client has this warranty:", "1 Year"],
		"quanity": ["Quanity:", "1"],
		"price": ["Price", "$1045.00"],
		"notes": ["Notes:", "We installed a wireless access point and a sonic firewall for free wi-fi"]
	},
	"client16":{
		"id": ["Client ID:", "15182557"],
		"group": ["Install:", "AudioVideo"],
		"compname": ["Company Name:", "Detroit Auto"],
		"contname": ["Contact Name:", "Jason Cross"],
		"contphone": ["Contact Phone #", "724-594-1594"],
		"contemail": ["Contact Email:", "jasoncross@gmail.com"],
		"date": ["Install Date:", "2012-02-14"],
		"ipaddress": ["Ip Address:", "72.240.153.153"],
		"sysuser": ["System Username:", "admin1"],
		"syspass": ["System Password:", "admin"],
		"installed": ["The client has these systems installed:", "Audio / Video"],
		"warranty": ["The client has this warranty:", "1 Year"],
		"quanity": ["Quanity:", "20"],
		"price": ["Price", "$15995.00"],
		"notes": ["Notes:", "We installed 20 tv's for customers to view specials on while in the store."]
	},
		"client17": {
		"id": ["Client ID:", "30158185"],
		"group": ["Install:", "POS"],
		"compname": ["Company Name:", "Velocity"],
		"contname": ["Contact Name:", "Don Sharpe"],
		"contphone": ["Contact Phone #", "724-506-1506"],
		"contemail": ["Contact Email:", "don@velocity.com"],
		"date": ["Install Date:", "2013-02-02"],
		"ipaddress": ["Ip Address:", "192.168.1.100"],
		"sysuser": ["System Username:", "don"],
		"syspass": ["System Password:", "don1506"],
		"installed": ["The client has these systems installed:", "POS"],
		"warranty": ["The client has this warranty:", "5 Year"],
		"quanity": ["Quanity:", "2"],
		"price": ["Price", "$8595.00"],
		"notes": ["Notes:", "We installed 2 POS systems on the front count to control inventory and to check out customers."]			
	},
	"client18":{
		"id": ["Client ID:", "21754202"],
		"group": ["Install:", "Surveillance"],
		"compname": ["Company Name:", "Haggopian"],
		"contname": ["Contact Name:", "Brian Hall"],
		"contphone": ["Contact Phone #", "724-653-1653"],
		"contemail": ["Contact Email:", "brianhall@gmail.com"],
		"date": ["Install Date:", "2012-03-20"],
		"ipaddress": ["Ip Address:", "192.168.1.110"],
		"sysuser": ["System Username:", "brian"],
		"syspass": ["System Password:", "admin"],
		"installed": ["The client has these systems installed:", "Surveillance"],
		"warranty": ["The client has this warranty:", "3 Year"],
		"quanity": ["Quanity:", "16"],
		"price": ["Price", "$7995.00"],
		"notes": ["Notes:", "We installed 16 cameras throughout the warehouse."]
	},
	"client19":{
		"id": ["Client ID:", "15972380"],
		"group": ["Install:", "Network"],
		"compname": ["Company Name:", "Holiday Inn Express"],
		"contname": ["Contact Name:", "Pat Allen"],
		"contphone": ["Contact Phone #", "412-684-1684"],
		"contemail": ["Contact Email:", "patallen@holidayinn.com"],
		"date": ["Install Date:", "2012-11-11"],
		"ipaddress": ["Ip Address:", "192.168.001.80"],
		"sysuser": ["System Username:", "patallen"],
		"syspass": ["System Password:", "123456"],
		"installed": ["The client has these systems installed:", "Network"],
		"warranty": ["The client has this warranty:", "3 Year"],
		"quanity": ["Quanity:", "3"],
		"price": ["Price", "$10995.00"],
		"notes": ["Notes:", "We installed 3 48 port network switches in the rack in the electrical room."]
	},
	"client20":{
		"id": ["Client ID:", "22364117"],
		"group": ["Install:", "AudioVideo"],
		"compname": ["Company Name:", "Sloan Industries"],
		"contname": ["Contact Name:", "Lynne Rose"],
		"contphone": ["Contact Phone #", "734-802-8679"],
		"contemail": ["Contact Email:", "lynnerose@gmail.com"],
		"date": ["Install Date:", "2013-01-23"],
		"ipaddress": ["Ip Address:", "192.168.0.153"],
		"sysuser": ["System Username:", "guest"],
		"syspass": ["System Password:", "guest"],
		"installed": ["The client has these systems installed:", "Audio / Video"],
		"warranty": ["The client has this warranty:", "90 Days"],
		"quanity": ["Quanity:", "4"],
		"price": ["Price", "$3995.00"],
		"notes": ["Notes:", "We installed 4 speakers in the office area hooked up to a receiver that they play pandora off of."]
	}
}